# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-cTpyKQhth9dEz0GJCpLpw4BTXA4u58
"""

# Script en PyMOL para identificar aminoácidos que interactúan con los ligandos nombrados como 'lig'

# Obtener todos los objetos que tienen el nombre 'lig'
ligandos = cmd.get_names('objects', selection="lig*")

# Iterar sobre cada ligando
for ligando in ligandos:
    # Seleccionar el ligando actual
    cmd.select("lig", f"{ligando}")

    # Seleccionar los aminoácidos dentro de un radio de 4 Å alrededor del ligando
    cmd.select("interacciones", "lig around 4 and polymer")

    # Obtener los nombres de los residuos que interactúan
    interacciones_residues = cmd.get_model("interacciones").get_residues()

    # Imprimir los residuos que interactúan con el ligando
    print(f"Ligando: {ligando}")
    print("Aminoácidos que interactúan:")

    # Evitar duplicados al mostrar los residuos
    residuo_visto = set()
    for res in interacciones_residues:
        residuo_nombre = f"{res.chain}/{res.resn}{res.resi}"
        if residuo_nombre not in residuo_visto:
            print(residuo_nombre)
            residuo_visto.add(residuo_nombre)

    # Limpiar las selecciones antes de pasar al siguiente ligando
    cmd.delete("lig")
    cmd.delete("interacciones")