# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kop-Gzz1gMjQhnCryuFqEcvmP2pk4V2j
"""

# Obtener una lista de todos los objetos que contienen "TioT"hola
ligands = cmd.get_object_list("lig_palmitico")

# Comparar todos los ligandos entre sí
for i in range(len(ligands)):
    for j in range(i+1, len(ligands)):
        ligand1 = ligands[i]
        ligand2 = ligands[j]
        # Calcular el RMS usando rms_cur
        rms_value = cmd.rms_cur(ligand1, ligand2)
        # Imprimir los resultados
        print(f"RMS between {ligand1} and {ligand2}: {rms_value}")