# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-cTpyKQhth9dEz0GJCpLpw4BTXA4u58
"""

# Script en PyMOL para identificar aminoácidos que interactúan con los ligandos nombrados como 'lig'

# Obtener todos los objetos que tienen el nombre 'lig'
ligandos = cmd.get_names('objects', selection="lig*")

# Iterar sobre cada ligando
for ligando in ligandos:
    # Seleccionar el ligando actual
    cmd.select("lig", f"{ligando}")

    # Seleccionar los aminoácidos dentro de un radio de 4 Å alrededor del ligando
    cmd.select("interacciones", "lig around 4 and polymer")

    # Obtener el modelo de los átomos que interactúan
    interacciones_model = cmd.get_model("interacciones")

    # Imprimir el nombre del ligando
    print(f"Ligando: {ligando}")
    print("Aminoácidos que interactúan:")

    # Crear un conjunto para almacenar los residuos únicos
    residuo_visto = set()

    # Iterar sobre los átomos del modelo de interacciones
    for atom in interacciones_model.atom:
        # Crear una identificación única para cada residuo (cadena, nombre del residuo y número)
        residuo_nombre = f"{atom.chain}/{atom.resn}{atom.resi}"

        # Si el residuo no ha sido visto, lo agregamos al conjunto y lo imprimimos
        if residuo_nombre not in residuo_visto:
            print(residuo_nombre)
            residuo_visto.add(residuo_nombre)

    # Limpiar las selecciones antes de pasar al siguiente ligando
    cmd.delete("lig")
    cmd.delete("interacciones")